# Source files
source ~/.path
source ~/.aliases
source ~/.exports
source ~/.private

# Source prompt
source ~/.zsh_prompt_pure

# List directory contents after cd
function cd {
  builtin cd "$@" && ls -a -F
}

#
# fzf
#

source <(fzf --zsh)

#
# z
#

source ~/.config/zsh/zsh-z/zsh-z.plugin.zsh

# Case insensitive completion

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' menu select

autoload -U promptinit; promptinit
autoload -Uz compinit && compinit

test -f "$HOME/h/config/envrc" -a -z "$NODE_VIRTUAL_ENV" && source "$HOME/h/config/envrc" # Generated by configure_node_if_necessary.js
