import = ["~/.config/alacritty/base16-greyscale-light.toml"]

[window]
dimensions = { columns = 80, lines = 40 }
padding = { x = 4, y = 8 }

[font]
size = 15
normal = { family = "SF Mono", style = "Regular" }
bold = { family = "SF Mono", style = "Regular" }
italic = { family = "SF Mono", style = "Regular" }

[colors]
draw_bold_text_with_bright_colors = true
