import = ["~/.config/alacritty/neovim-default-light.toml"]

[window]
dimensions = { columns = 80, lines = 40 }
padding = { x = 4, y = 8 }

[font]
size = 15
normal = { family = "SFMono Nerd Font", style = "Regular" }
bold = { family = "SFMono Nerd Font", style = "Regular" }
italic = { family = "SFMono Nerd Font", style = "Regular" }
